Repository NIAEFEUP/tts-fe, pull requests merged in 2022-08, with the labels that each got.

#94 Config file for path
  src/App.tsx
  src/api/backend.ts
  src/components/layout/Header.tsx
  src/components/planner/SelectionModal.tsx
  src/config/default.json
  src/utils/index.ts
Labels: high priority, low effort, devops

#95 Path fix.
  src/components/home/HeroPlanner.tsx
  src/components/layout/Header.tsx
  src/components/planner/HelpModal.tsx
  src/pages/NotFound.tsx
Labels: bug, high priority, low effort

#98 Professors without weekday - wrong range
  src/utils/index.ts
Labels: bug

#100 Practical lesson are represented as array
  src/@types/index.d.ts
  src/components/planner/Schedule.tsx
  src/components/planner/ScheduleListbox.tsx
Labels: bug, high priority, low effort
